// Types automatically generated by SvelteKit.
import type { PageLoad } from "./$types";
// Custom types.
import type { tempT } from "$lib";

export const load: PageLoad = async ({ fetch }) => {
  const res = await fetch("/temp.json");
  const temp = await res.json() as tempT;

  return { temp };
};
